#!/usr/bin/env bash
# install-cron.sh - Print or install crontab entries for Hermes Memory Compiler
set -euo pipefail

# Derive absolute project root from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

FLUSH_LINE="*/30 * * * * cd $PROJECT_ROOT && python3 scripts/flush.py --all >> scripts/flush.log 2>&1"
COMPILE_LINE="0 18 * * * cd $PROJECT_ROOT && python3 scripts/compile.py >> scripts/compile.log 2>&1"

print_entries() {
    echo "# Hermes Memory Compiler cron jobs"
    echo "# Generated by scripts/install-cron.sh"
    echo "$FLUSH_LINE"
    echo "$COMPILE_LINE"
}

install_entries() {
    TMPFILE=$(mktemp)
    trap 'rm -f "$TMPFILE"' EXIT

    # Capture existing crontab, or empty if none exists
    crontab -l > "$TMPFILE" 2>/dev/null || true

    local added=0

    if ! grep -qxF "$FLUSH_LINE" "$TMPFILE"; then
        echo "$FLUSH_LINE" >> "$TMPFILE"
        added=$((added + 1))
    fi

    if ! grep -qxF "$COMPILE_LINE" "$TMPFILE"; then
        echo "$COMPILE_LINE" >> "$TMPFILE"
        added=$((added + 1))
    fi

    if [ "$added" -eq 0 ]; then
        echo "Cron entries already present. No changes made."
    else
        crontab "$TMPFILE"
        echo "Installed $added cron entr(y/ies)."
    fi
}

case "${1:-}" in
    --install)
        install_entries
        ;;
    *)
        print_entries
        ;;
esac
